//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleclient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cal", Namespace="http://schemas.datacontract.org/2004/07/_1104example")]
    [System.SerializableAttribute()]
    public partial class Cal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int num1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int num2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char operField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num1 {
            get {
                return this.num1Field;
            }
            set {
                if ((this.num1Field.Equals(value) != true)) {
                    this.num1Field = value;
                    this.RaisePropertyChanged("num1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num2 {
            get {
                return this.num2Field;
            }
            set {
                if ((this.num2Field.Equals(value) != true)) {
                    this.num2Field = value;
                    this.RaisePropertyChanged("num2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char oper {
            get {
                return this.operField;
            }
            set {
                if ((this.operField.Equals(value) != true)) {
                    this.operField = value;
                    this.RaisePropertyChanged("oper");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IExample")]
    public interface IExample {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/GetExample", ReplyAction="http://tempuri.org/IExample/GetExampleResponse")]
        exampleclient.ServiceReference1.Cal[] GetExample(int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/GetExample", ReplyAction="http://tempuri.org/IExample/GetExampleResponse")]
        System.Threading.Tasks.Task<exampleclient.ServiceReference1.Cal[]> GetExampleAsync(int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/InputExample", ReplyAction="http://tempuri.org/IExample/InputExampleResponse")]
        bool InputExample(int num1, int num2, char oper, float input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/InputExample", ReplyAction="http://tempuri.org/IExample/InputExampleResponse")]
        System.Threading.Tasks.Task<bool> InputExampleAsync(int num1, int num2, char oper, float input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/PrintExample", ReplyAction="http://tempuri.org/IExample/PrintExampleResponse")]
        string PrintExample(int num1, int num2, char oper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/PrintExample", ReplyAction="http://tempuri.org/IExample/PrintExampleResponse")]
        System.Threading.Tasks.Task<string> PrintExampleAsync(int num1, int num2, char oper);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExampleChannel : exampleclient.ServiceReference1.IExample, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExampleClient : System.ServiceModel.ClientBase<exampleclient.ServiceReference1.IExample>, exampleclient.ServiceReference1.IExample {
        
        public ExampleClient() {
        }
        
        public ExampleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExampleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public exampleclient.ServiceReference1.Cal[] GetExample(int max) {
            return base.Channel.GetExample(max);
        }
        
        public System.Threading.Tasks.Task<exampleclient.ServiceReference1.Cal[]> GetExampleAsync(int max) {
            return base.Channel.GetExampleAsync(max);
        }
        
        public bool InputExample(int num1, int num2, char oper, float input) {
            return base.Channel.InputExample(num1, num2, oper, input);
        }
        
        public System.Threading.Tasks.Task<bool> InputExampleAsync(int num1, int num2, char oper, float input) {
            return base.Channel.InputExampleAsync(num1, num2, oper, input);
        }
        
        public string PrintExample(int num1, int num2, char oper) {
            return base.Channel.PrintExample(num1, num2, oper);
        }
        
        public System.Threading.Tasks.Task<string> PrintExampleAsync(int num1, int num2, char oper) {
            return base.Channel.PrintExampleAsync(num1, num2, oper);
        }
    }
}
